[project]
name = "dt-post"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Dimitrios Tsiktsiris", email = "dtsiktsiris@outlook.com" }
]
requires-python = ">=3.14"
dependencies = [
    "python-jsonpath==2.2.1",
    "PyYAML==6.0.3",
    "requests==2.34.2"
]

[project.scripts]
dt-post = "dt_post.main:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
